**EXPERIMENT 5**<br>
Aim: To study and perform Multiple Linear Regression model.

In [ ]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from google.colab import files
uploaded = files.upload()

Saving homeprice_new.csv to homeprice_new.csv


In [ ]:
df = pd.read_csv('homeprice_new.csv')
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Data Preprocessing: Fill NA values with median value of a column

In [ ]:
df.Bedrooms.median()

4.0

In [ ]:
df.Bedrooms = df.Bedrooms.fillna(df.Bedrooms.median())
df

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

Find X and Y

In [ ]:
X = df.drop('Price', axis='columns')
X

Area  Bedrooms  Age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [ ]:
Y = df.Price
Y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: Price, dtype: int64

Fit Linear Regression Model

In [ ]:
reg = linear_model.LinearRegression()
reg.fit(X,Y)

LinearRegression()

In [ ]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [ ]:
reg.intercept_

221323.00186540396

In [ ]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [ ]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])